build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-npm
    when:
      branch: master

plugin:
  name: NPM
  desc: Publish a node package to the npm registry.
  type: publish
  image: plugins/drone-node
  labels:
    - publish
    - node


